RowerOwO/Controllers/RentalPointController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using RowerOwO.Areas.Users.Data;
using RowerOwO.Database;
using RowerOwO.ViewModels;

namespace RowerOwO.Controllers
{
    public class RentalPointController : Controller
    {
        public RentalPointRepository rentalPointRepo;
        private readonly IMapper _mapper;

        public RentalPointController(DatabaseContext context, IMapper mapper)
        {
            rentalPointRepo = new(context);
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            List<RentalPointCRUDViewModel> rentalPointList = new();

            foreach (var item in rentalPointRepo.GetAll())
            {
                rentalPointList.Add(_mapper.Map<RentalPointCRUDViewModel>(item));
                //rentalPointList.Add(new RentalPointCRUDViewModel()
                //{
                //    Id = item.Id,
                //    Name = item.Name,
                //    City = item.City,
                //    Street = item.Street,
                //    Number = item.Number
                //});
            }

            return View(rentalPointList);
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit(Guid id)
        {
            var selectedRentalPoint = rentalPointRepo.Get(id);

            //var editViewModel = new RentalPointCRUDViewModel()
            //{
            //    Id = selectedRentalPoint.Id,
            //    Name = selectedRentalPoint.Name,
            //    City = selectedRentalPoint.City,
            //    Street = selectedRentalPoint.Street,
            //    Number = selectedRentalPoint.Number
            //};

            var editViewModel = _mapper.Map<RentalPointCRUDViewModel>(selectedRentalPoint);

            return View(editViewModel);
        }

        public ActionResult CreateSubmit(string name, string city, string street, string number)
        {
            rentalPointRepo.Create(name, city, street, number);

            return RedirectToAction("Index");
        }

        public ActionResult EditSubmit(Guid id, string Name, string City, string Street, string Number)
        {
            rentalPointRepo.Edit(id, Name, City, Street, Number);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid id)
        {
            rentalPointRepo.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

RowerOwO/Controllers/VehicleController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RowerOwO.Areas.Users.Data;
using RowerOwO.Database;
using RowerOwO.Database.Repos;
using RowerOwO.Models;
using RowerOwO.ViewModels;
using System.Security.Cryptography.X509Certificates;

namespace RowerOwO.Controllers
{
    public class VehicleController : Controller
    {
        public VehicleRepository vehicleRepo;
        public RentalRepository rentalRepo;
        public RentalPointRepository rentalPointRepo;
        private readonly IMapper _mapper;

        public VehicleController(DatabaseContext context, IMapper mapper)
        {
            vehicleRepo = new(context);
            rentalRepo = new(context);
            rentalPointRepo = new(context);
            _mapper = mapper;
        }

        // GET: BikeController
        public ActionResult Index()
        {
            List<VehicleListViewModel> vehicleList = new();

            foreach (var item in vehicleRepo.GetAll())
            {
                vehicleList.Add(_mapper.Map<VehicleListViewModel>(item));
                //new VehicleListViewModel()
                //{
                //    Id = item.Id,
                //    Name = item.Name,
                //    IsAvailable = item.IsAvailable,
                //    ImgPath = item.ImgPath,
                //    Description = item.Description,
                //    Type = item.Type
                //}
            }

            return View(vehicleList);
        }

        public ActionResult Details(Guid id)
        {
            var selectedVehicle = vehicleRepo.Get(id);

            //VehicleDetailsViewModel detailViewModel = new VehicleDetailsViewModel()
            //{
            //    Id = selectedVehicle.Id,
            //    Name = selectedVehicle.Name,
            //    ImgPath = selectedVehicle.ImgPath,
            //    Description = selectedVehicle.Description,
            //    Powered = selectedVehicle.Powered,
            //    Color = selectedVehicle.Color,
            //    RentPrice = selectedVehicle.RentPrice,
            //    Type = selectedVehicle.Type
            //};

            var detailViewModel = _mapper.Map<VehicleDetailsViewModel>(selectedVehicle);

            return View(detailViewModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit(Guid id)
        {
            var selectedVehicle = vehicleRepo.Get(id);

            //VehicleEditViewModel editViewModel = new VehicleEditViewModel()
            //{
            //    Id = selectedVehicle.Id,
            //    Name = selectedVehicle.Name,
            //    ImgPath = selectedVehicle.ImgPath,
            //    Description = selectedVehicle.Description,
            //    Powered = selectedVehicle.Powered,
            //    Color = selectedVehicle.Color,
            //    RentPrice = selectedVehicle.RentPrice,
            //    Type = selectedVehicle.Type
            //};

            var editViewModel = _mapper.Map<VehicleEditViewModel>(selectedVehicle);

            return View(editViewModel);
        }

        [HttpPost]
        public ActionResult CreateSubmit(string Name, string ImgPath, string Description, bool Powered, string Color, double RentPrice, string Type)
        {
            if (ImgPath == null)
            {
                ImgPath = "\\img\\bikeDefault.png";
            }
            vehicleRepo.Create(Name, ImgPath, Description, Powered, Color, RentPrice, Type);
            return RedirectToAction("Index");
        }

        public ActionResult EditSubmit(Guid id,string Name, string Description, bool Powered, string Color, double RentPrice, string Type)
        {
            //ImgPath doesen't change for now
            vehicleRepo.Edit(id, Name, Description, Powered, Color, RentPrice, Type);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid id)
        {
            vehicleRepo.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

RowerOwO/Views/Shared/_Layout.cshtml
@{
	var loggerUser = User?.Identity?.Name ?? "";
	if (User?.Identity?.IsAuthenticated == false && loggerUser != "")
	{
		loggerUser = "";
	}
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - RowerOwO</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
	<link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/RowerOwO.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rower<font color="#FFACAC">OwO</font></a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						@*<li class="nav-item">
						<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>*@
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Vehicle" asp-action="Index">Oferta</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="RentalPoint" asp-action="Index">Punkty wypożyczeń</a>
						</li>
						@if (loggerUser == "")
						{
							<li class="nav-item ms-auto">
								<a class="nav-link text-dark" style="background: #FFACAC; border-radius: 20px;" href="/Login"><i class="bi bi-person-circle" style="color:white;"></i></a>
							</li>
						}
						else
						{
							<li class="nav-item ms-auto">
								<p>@loggerUser</p>
							</li>
							<li class="nav-item ms-auto">
								<a class="nav-link text-dark" style="background: #FFACAC; border-radius: 20px;" href="/Logout"><i class="bi bi-box-arrow-right"></i></a>
							</li>
						}
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - RowerOwO - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>